---
- name: 'Create node_exporter system group'
  ansible.builtin.group:
    name: 'node_exporter'
    state: present
    system: true
  become: true

- name: 'Create node_exporter system user'
  ansible.builtin.user:
    name: 'node_exporter'
    group: 'node_exporter'
    shell: '/usr/sbin/nologin'
    state: present
    system: true
  become: true

- name: 'Install node_exporter'
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/\
      v{{ node_exporter_version }}/\
      node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: '/usr/local/bin'
    remote_src: true
    extra_opts:
      - '--strip-components=1'
      - '--wildcards'
      - '*/node_exporter'
  become: true

- name: 'Configure node_exporter systemd service'
  ansible.builtin.copy:
    dest: '/etc/systemd/system/node_exporter.service'
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter \
        --web.listen-address={{ node_exporter_web_listen_address }} \
        --web.telemetry-path={{ node_exporter_web_telemetry_path }}

      [Install]
      WantedBy=multi-user.target
  become: true
  notify: 'Reload node_exporter'

- name: 'Start and enable node_exporter'
  ansible.builtin.service:
    name: 'node_exporter'
    state: started
    enabled: true
  become: true
