repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: kubernetes/charts/.*/templates/
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.108.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl

  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.3.2
    hooks:
      - id: checkov
        args:
          - --directory
          - terraform/
          - --quiet
          - --compact
          - --skip-check
          - CKV2_AWS_12,CKV2_AWS_5,CKV2_AWS_41,CKV_AWS_130,CKV_AWS_157,CKV2_AWS_11,CKV2_AWS_30,CKV_AZURE_50,CKV_AZURE_43,CKV_AZURE_119,CKV2_AZURE_1,CKV2_AZURE_21,CKV2_AZURE_31,CKV2_AZURE_33,CKV2_AZURE_40,CKV2_AZURE_41,CKV2_AZURE_57,CKV_AZURE_206,CKV_K8S_14,CKV_K8S_15,CKV_K8S_21,CKV_K8S_35,CKV_K8S_43,CKV_SECRET_4,CKV_SECRET_6

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [-c, .yamllint.yml]
        exclude: kubernetes/charts/.*/templates/

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        args: [--severity=warning]

  - repo: https://github.com/ansible/ansible-lint
    rev: v26.4.0
    hooks:
      - id: ansible-lint
        files: ansible/
