extends: default

rules:
  line-length:
    max: 150
    allow-non-breakable-inline-mappings: true
  truthy:
    check-keys: false
    allowed-values: ["true", "false", "yes", "no"]
  comments:
    min-spaces-from-content: 1
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: consistent

ignore:
  - .venv/
  - kubernetes/charts/*/templates/
  - monitoring/grafana/dashboards/
