replicaCount: 1

image:
  repository: data-zoo/ingestor
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

probes:
  liveness:
    path: /health
  readiness:
    path: /readyz

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

env:
  environment: local

secrets:
  name: data-zoo-app-secrets
  databaseUrlKey: database_url
  brokerUrlKey: broker_url
  cacheUrlKey: cache_url
  adminTokenKey: admin_token

config:
  name: data-zoo-app-config
  inferenceUrlKey: inference_url
  otelEndpointKey: otel_exporter_otlp_endpoint
