apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-from-inference
  namespace: data-zoo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: inference
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 6333
          protocol: TCP
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
