apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-default-deny-all-ingress.yaml
  - 01-allow-ingress-to-ingestor.yaml
  - 02-allow-ingress-to-inference.yaml
  - 03-allow-ingress-to-analytics.yaml
  - 04-allow-ingress-to-dashboard.yaml
  - 05-restrict-egress-from-processor.yaml
  - 06-allow-egress-from-ingestor.yaml
  - 07-allow-egress-from-webhook.yaml
  - 08-allow-egress-from-analytics.yaml
  - 09-allow-egress-from-dashboard.yaml
  - 10-allow-egress-from-inference.yaml
