apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data-zoo
resources:
  - namespace.yaml
  - service-account.yaml
  - role.yaml
  - role-binding.yaml
  - config.yaml
  - ingestor-deployment.yaml
  - ingestor-service.yaml
  - ingestor-hpa.yaml
  - dashboard-deployment.yaml
  - dashboard-service.yaml
  - ingress.yaml
  - ../../manifests/network-policies
